---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
      disable_upstart: false

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
  - name: server
    run_list:
      - recipe[consul::default]
      - recipe[consul::ui]
    attributes:
      consul:
        mode: server
